name: Lint
on:
  push:
    branches:
      - server-python

jobs:
  test:
    strategy:
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pipenv
        run: pip install pipenv

      - name: Install python dependencies
        run: pipenv install

      - name: Lint code
        run: pipenv run lint
